Controllers/WebsiteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Website.Models;
using PagedList.Mvc;
using PagedList;
namespace Website.Controllers
{
    public class WebsiteController : Controller
    {
        dbWebsiteDataContext db = new dbWebsiteDataContext();
        // GET: Website
        private List<SANPHAM> LaySachNhieu(int count)
        {
            return db.SANPHAMs.OrderByDescending(s => s.SoLuongBan).Take(count).ToList();
        }
        private List<SANPHAM> LaySPMoi(int count)
        {
            return db.SANPHAMs.OrderByDescending(s => s.NgayCapNhat).Take(count).ToList();
        }
        public ActionResult Index()
        {
            var list = LaySPMoi(10);
            return View(list);
        }
        public ActionResult GioiThieu()
        {

            return View();
        }
        public ActionResult LapTop(int ?page,string sort)
        {
            int iSize = 9;
            int iPageNum = (page ?? 1);
            var laptop = from lt in db.SANPHAMs where lt.MaLoaiSP>0 && lt.MaLoaiSP<9 select lt;
            switch (sort)
            {
                case "spnoibat":
                    {
                        ViewBag.NameSort = "spnoibat";
                        laptop = laptop.OrderByDescending(s => s.NgayCapNhat);
                        break;
                    }
                case "tang":
                    {
                        ViewBag.NameSort = "tang";
                        laptop = laptop.OrderBy(s => s.GiaBan);
                        break;
                    }
                case "giam":
                    {
                        ViewBag.NameSort = "giam";
                        laptop = laptop.OrderByDescending(s => s.GiaBan);
                        break;
                    }
                default:
                    sort = null;
                    break;
            }
            return View(laptop.ToPagedList(iPageNum,iSize));
        }
        public ActionResult PhuKien(int ?page,string sort)
        {
            int iSize = 8;
            int iPageNum = (page ?? 1);
            var phukien = from pk in db.SANPHAMs where pk.MaLoaiSP > 15 && pk.MaLoaiSP < 24 select pk;
            switch (sort)
            {
                case "spnoibat":
                    {
                        ViewBag.NameSort = "spnoibat";
                        phukien = phukien.OrderByDescending(s => s.NgayCapNhat);
                        break;
                    }
                case "tang":
                    {
                        ViewBag.NameSort = "tang";
                        phukien = phukien.OrderBy(s => s.GiaBan);

                        break;
                    }
                case "giam":
                    {
                        ViewBag.NameSort = "giam";
                        phukien = phukien.OrderByDescending(s => s.GiaBan);
                        break;
                    }
                default:
                    sort = null;
                    break;
            }
            return View(phukien.ToPagedList(iPageNum,iSize));
        }
        public ActionResult LinhKien(int ?page,string sort)
        {
            int iSize = 8;
            int iPageNum = (page ?? 1);
            var linhkien = from lk in db.SANPHAMs where lk.MaLoaiSP > 9 && lk.MaLoaiSP < 15 select lk;
            switch (sort)
            {
                case "spnoibat":
                    {
                        ViewBag.NameSort = "spnoibat";
                        linhkien = linhkien.OrderByDescending(s => s.NgayCapNhat);
                        break;
                    }
                case "tang":
                    {
                        ViewBag.NameSort = "tang";
                        linhkien = linhkien.OrderBy(s => s.GiaBan);

                        break;
                    }
                case "giam":
                    {
                        ViewBag.NameSort = "giam";
                        linhkien = linhkien.OrderByDescending(s => s.GiaBan);
                        break;
                    }
                default:
                    sort = null;
                    break;
            }
            return View(linhkien.ToPagedList(iPageNum, iSize));
        }
        public ActionResult HienThiLapTop(int id,int? page)
        {
            ViewBag.MaLT = id;
            int iSize = 8;
            int iPageNum = (page ?? 1);
            var laptop = from pk in db.SANPHAMs where pk.MaLoaiSP == id select pk;
            return View(laptop.ToPagedList(iPageNum,iSize));
        }
        public ActionResult HienThiLapTopLoc(string loc, int? page)
        {

            int iSize = 9;
            int iPageNum = (page ?? 1);
            var laptop = from lt in db.SANPHAMs where lt.MaLoaiSP > 0 && lt.MaLoaiSP < 9 select lt;
            switch (loc)
            {
                case "duoi10":
                    ViewBag.Loc = loc;
                    laptop = laptop.Where(n => n.GiaBan < 10000000);
                    break;
                case "1015":
                    ViewBag.Loc = loc;
                    laptop = laptop.Where(n => n.GiaBan >= 10000000 && n.GiaBan<=15000000);
                    break;
                case "1520":
                    ViewBag.Loc = loc;
                    laptop = laptop.Where(n => n.GiaBan >= 15000000 && n.GiaBan <= 20000000);
                    break;
                case "2025":
                    ViewBag.Loc = loc;
                    laptop = laptop.Where(n => n.GiaBan >= 20000000 && n.GiaBan <= 25000000);
                    break;
                case "tren25":
                    ViewBag.Loc = loc;
                    laptop = laptop.Where(n => n.GiaBan > 25000000);
                    break;
                case "4gb":
                    ViewBag.Loc = loc;
                    laptop = laptop.Where(n=>n.RAM=="4GB");
                    break;
                case "8gb":
                    ViewBag.Loc = loc;
                    laptop = laptop.Where(n => n.RAM == "8GB");
                    break;
                case "16gb":
                    ViewBag.Loc = loc;
                    laptop = laptop.Where(n => n.RAM == "16GB");
                    break;
               
                
            }
            return View(laptop.ToPagedList(iPageNum, iSize));
        }
        public ActionResult HienThiPhuKien(int id,int ?page,string sort)
        {
            ViewBag.MaPK = id;
            int iSize = 8;
            int iPageNum = (page ?? 1);
            var phukien = from pk in db.SANPHAMs where pk.MaLoaiSP==id select pk;
            switch (sort)
            {
                case "spnoibat":
                    {
                        ViewBag.NameSort = "spnoibat";
                        phukien = phukien.OrderByDescending(s => s.NgayCapNhat);
                        break;
                    }
                case "tang":
                    {
                        ViewBag.NameSort = "tang";
                        phukien = phukien.OrderBy(s => s.GiaBan);

                        break;
                    }
                case "giam":
                    {
                        ViewBag.NameSort = "giam";
                        phukien = phukien.OrderByDescending(s => s.GiaBan);
                        break;
                    }
                default:
                    sort = null;
                    break;
            }
            return View(phukien.ToPagedList(iPageNum, iSize));
        }
        public ActionResult HienThiLinhKien(int id,int ?page,string sort)
        {
            ViewBag.MaLK = id;
            int iSize = 8;
            int iPageNum = (page ?? 1);
            var linhkien = from lk in db.SANPHAMs where lk.MaLoaiSP == id select lk;
            switch (sort)
            {
                case "spnoibat":
                    {
                        ViewBag.NameSort = "spnoibat";
                        linhkien = linhkien.OrderByDescending(s => s.NgayCapNhat);
                        break;
                    }
                case "tang":
                    {
                        ViewBag.NameSort = "tang";
                        linhkien = linhkien.OrderBy(s => s.GiaBan);

                        break;
                    }
                case "giam":
                    {
                        ViewBag.NameSort = "giam";
                        linhkien = linhkien.OrderByDescending(s => s.GiaBan);
                        break;
                    }
                default:
                    sort = null;
                    break;
            }
            return View(linhkien.ToPagedList(iPageNum, iSize));
        }
        public ActionResult HeaderPartial()
        {
            return PartialView();
        }
        public ActionResult NavPartial()
        {
            return PartialView();
        }
        public ActionResult SliderPartial()
        {
            return PartialView();
        }
        public ActionResult BanNhieuPartial()
        {
            var listSachNhieu = LaySachNhieu(10);
            return PartialView(listSachNhieu);
            
        }
        public ActionResult FooterPartial()
        {
            return PartialView();
        }
        [HttpGet]
        public ActionResult LienHe()
        {
            return View();
        }
        [HttpPost]
        public ActionResult LienHe(FormCollection collection,LIENHE lh)
        {
            var sHoTen = collection["HoTen"];
            var sEmail = collection["Email"];
            var sNoiDung = collection["NoiDung"];
            if (ModelState.IsValid)
            {
                
                lh.HoTen = sHoTen;
                lh.Email = sEmail;
                lh.NoiDung = sNoiDung;
                db.LIENHEs.InsertOnSubmit(lh);
                db.SubmitChanges();

Views/Shared/HeaderPartial.cshtml
@using Website.Models
@{
    KHACHHANG kh = (KHACHHANG)Session["TaiKhoan"];
}
<style>
    .header-search form .input {
        width: calc(100% - 100px);
        margin-right: -4px;
        border-radius: 40px 0px 0px 40px;
    }
</style>
<header>
    <!-- TOP HEADER -->
    <div id="top-header">
        <div class="container" style="padding-right: 70px; height: 30px;">
            <ul class="header-links pull-left" style="padding-top:10px;">
                <li><a href="#"><i class="glyphicon glyphicon-phone"></i> 0962579454</a></li>
                <li><a href="#"><i class="glyphicon glyphicon-envelope"></i> nguyenhuunhan3354@gmail.com</a></li>
                <li><a href="#"><i class="glyphicon glyphicon-map-marker"></i>Thủ Dầu Một, Bình Dương</a></li>
            </ul>
            @if (Session["TaiKhoan"] == null)
            {
                <ul class="header-links pull-right" style="padding-top:10px;">
                    
                    <li><a href="@Url.Action("DangNhap", "User")"><i class="fa fa-user-o"></i> Tài khoản của tôi</a></li>
                </ul>
            }
            else
            {
                <ul class="header-links pull-right" style="padding-top:10px;">
                    
                    <li><a href="#"><i class="fa fa-user-o"></i> @kh.TenKH</a></li>
                    <li><a href="@Url.Action("DangXuat","User")"><i class="fa fa-sign-out"></i>Đăng xuất</a></li>
                </ul>
            }
        </div>
    </div>
    <!-- /TOP HEADER -->
    <!-- MAIN HEADER -->
    <div id="header">
        <!-- container -->
        <div class="container">
            <!-- row -->
            <div class="row">
                <!-- LOGO -->
                <div class="col-md-3">
                    <div class="header-logo">
                        <a class="logo" href="#"><img src="~/Images/logoweb.png" style="width:220px;display:block;" /></a>
                    </div>
                </div>
                <!-- /LOGO -->
                <!-- SEARCH BAR -->
                <div class="col-md-6">
                    <div class="header-search">

                        @using (Html.BeginForm("Search", "Search", FormMethod.Get, new { @role = "search" }))
                        {
                            <input class="input" placeholder="Nhập từ khóa tìm kiếm..." name="name" value="@ViewBag.Search">
                            <button class="search-btn" type="submit"><span class="glyphicon glyphicon-search"></span></button>
                        }
                    </div>
                </div>
                <!-- /SEARCH BAR -->
                <!-- ACCOUNT -->
                
                    <div class="col-md-3 clearfix">
                        <div class="header-ctn">
                            <!-- Wishlist -->
                            <div>
                                <a href="@Url.Action("YeuThich","YeuThich")">
                                    <i class="fa fa-heart-o"></i>
                                    <span>Yêu thích</span>
                                </a>
                            </div>
                            <!-- /Wishlist -->
                            <!-- Cart -->
                            <div class="dropdown">
                                <a href="@Url.Action("GioHang","GioHang")">
                                    <i class="glyphicon glyphicon-shopping-cart"></i>
                                    <span> Giỏ hàng</span>
                                </a>
                                @*
                            <div class="cart-dropdown">
                                <div class="cart-list">
                                    <div class="product-widget">
                                        <div class="product-img">
                                            <img src="~/Images/product01.png" alt="">
                                        </div>
                                        <div class="product-body">
                                            <h3 class="product-name"><a href="#">product name goes here</a></h3>
                                            <h4 class="product-price"><span class="qty">1x</span>$980.00</h4>
                                        </div>
                                        <button class="delete"><i class="fa fa-close"></i></button>
                                    </div>
                                    <div class="product-widget">
                                        <div class="product-img">
                                            <img src="~/Images/product02.png" alt="">
                                        </div>
                                        <div class="product-body">
                                            <h3 class="product-name"><a href="#">product name goes here</a></h3>
                                            <h4 class="product-price"><span class="qty">3x</span>$980.00</h4>
                                        </div>
                                        <button class="delete"><i class="fa fa-close"></i></button>
                                    </div>
                                </div>
                                <div class="cart-summary">
                                    <small>3 Item(s) selected</small>
                                    <h5>SUBTOTAL: $2940.00</h5>
                                </div>
                                <div class="cart-btns">
                                    <a href="#">View Cart</a>
                                    <a href="#">Checkout  <i class="fa fa-arrow-circle-right"></i></a>
                                </div>
                            </div>
                        </div>
                                *@
                                <!-- /Cart -->
                                <!-- Menu Toogle -->
                                <div class="menu-toggle">
                                    <a href="#">
                                        <i class="fa fa-bars"></i>
                                        <span>Menu</span>
                                    </a>
                                </div>
                                <!-- /Menu Toogle -->
                            </div>
                        </div>
                    </div>
                
                
                <!-- /ACCOUNT -->
            </div>
                <!-- row -->
            </div>
            <!-- container -->
        </div>
        <!-- /MAIN HEADER -->
</header>

Views/Shared/NavPartial.cshtml
<!-- NAVIGATION -->
<style>
    .main-nav > li > a:after {
        content: "";
        display: block;
        width: 0%;
        height: 2px;
        background-color: #D10024;
        -webkit-transition: 0.2s all;
        transition: 0.2s all;
    }
</style>
<nav id="navigation">
    <!-- container -->
    <div class="container">
        <!-- responsive-nav -->
        <div id="responsive-nav">
            <!-- NAV -->
            <ul class="main-nav nav navbar-nav">
                <li><a href="@Url.Action("Index","Website")">TRANG CHỦ</a></li>
                <li><a href="@Url.Action("GioiThieu","Website")">GIỚI THIỆU</a></li>
                <li><a href="@Url.Action("LapTop","Website")">LAPTOP</a></li>
                <li><a href="@Url.Action("LinhKien","Website")">LINH KIỆN PC</a></li>
                <li><a href="@Url.Action("PhuKien","Website")">PHỤ KIỆN</a></li>
                <li><a href="@Url.Action("TinTuc","Website")">TIN TỨC</a></li>
                <li><a href="@Url.Action("LienHe","Website")">LIÊN HỆ</a></li>

            </ul>
            <!-- /NAV -->
        </div>
        <!-- /responsive-nav -->
    </div>
    <!-- /container -->
</nav>
<!-- /NAVIGATION -->

Views/Shared/SliderPartial.cshtml
<br />

        <div class="col-lg-12">
            <div id="carousel1" class="carousel slide">
                
                <div class="carousel-inner">
                    <div class="item active">
                        <img class="img-responsive" src="~/Images/Slider/05.png" alt="thumb" width="100%">
                        <!--<div class="carousel-caption"> Quảng cáo 1 </div>-->
                    </div>
                    <div class="item">
                        <img class="img-responsive" src="~/Images/Slider/04.png" alt="thumb"width="100%">

                        <!--<div class="carousel-caption"> Quảng cáo 2 </div>-->
                    </div>
                    <div class="item">
                        <img class="img-responsive" src="~/Images/Slider/06.png" alt="thumb"width="100%">

                        <!--<div class="carousel-caption"> Quảng cáo 2 </div>-->
                    </div>
                    
                </div>
                <a class="left carousel-control" href="#carousel1" data-slide="prev"><span class="icon-prev"></span></a>
                <a class="right carousel-control" href="#carousel1" data-slide="next"><span class="icon-next"></span></a>
            </div>
        </div>
   

Views/Shared/_LayoutWebsite.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/bootstrap")
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <link href="~/Content/css/style.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <script src='https://kit.fontawesome.com/a076d05399.js' crossorigin='anonymous'></script>
    
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
    <style>
        body {
            display: inline;
        }
    </style>
    <!-- HEADER -->
    @Html.Action("HeaderPartial", "Website")
    <!-- /HEADER -->
    <!-- NAVIGATION -->
    @Html.Action("NavPartial", "Website")
    <!--SLIDER-->
    @RenderSection("Slider",required:false)
    <!-- FOOTER -->

    <div>
        @RenderSection("Phukien",required:false)
        @RenderBody()
    </div>
    @RenderSection("BanNhieu", required: false)

    <footer id="footer">
        <!-- top footer -->
        <div class="section">
            <!-- container -->
            <div class="container">
                <!-- row -->
                <div class="row">
                    <div class="col-md-3 col-xs-6">
                        <div class="footer">
                            <h3 class="footer-title">Thông tin công ty</h3>
                            <p>NHNComShop là một trong những cửa hàng uy tín và chất lượng hàng đầu Việt Nam.</p>
                            <ul class="footer-links">
                                <li><a href="#">Giới thiệu</a></li>
                                <li><a href="#">Liên hệ</a></li>
                                <li><a href="#"><i class="glyphicon glyphicon-map-marker"></i>Thủ Dầu Một, Bình Dương</a></li>
                                <li><a href="#"><i class="glyphicon glyphicon-phone"></i>0962579454</a></li>
                                <li><a href="#"><i class="glyphicon glyphicon-envelope"></i>nguyenhuunhan3354@gmail.com</a></li>
                            </ul>
                        </div>
                    </div>

                    <div class="col-md-3 col-xs-6">
                        <div class="footer">
                            <h3 class="footer-title">Danh mục sản phẩm</h3>
                            <ul class="footer-links">
                                <li><a href="@Url.Action("LapTop","Website")">LapTop</a></li>
                                <li><a href="@Url.Action("LinhKien","Website")">Linh kiện PC</a></li>
                                <li><a href="@Url.Action("PhuKien","Website")">Phụ kiện</a></li>
                                <li><a href="@Url.Action("TinTuc","Website")">Tin tức</a></li>
                            </ul>
                        </div>
                    </div>



                    <div class="col-md-3 col-xs-6">
                        <div class="footer">
                            <h3 class="footer-title">Chính sách</h3>
                            <ul class="footer-links">
                                <li><a href="#">Chính sách bảo mật</a></li>
                                <li><a href="#">Chính sách vận chuyển</a></li>
                                <li><a href="#">Chính sách bảo hành</a></li>
                                <li><a href="#">Chính sách đổi trả</a></li>
                            </ul>
                        </div>
                    </div>

                    <div class="col-md-3 col-xs-6">
                        <div class="footer">
                            <h3 class="footer-title">Hỗ trợ khách hàng</h3>
                            <ul class="footer-links">
                                <li><a href="#">Câu hỏi thường gặp</a></li>
                                <li><a href="#">Hướng dẫn mua hàng</a></li>
                                <li><a href="#">Hướng dẫn thanh toán</a></li>

                            </ul>
                        </div>
                    </div>
                </div>
                <!-- /row -->
            </div>
            <!-- /container -->
        </div>
        <!-- /top footer -->
        <!-- bottom footer -->

        <div id="bottom-footer" class="section">
            <div class="container">
                <!-- row -->
                <div class="row">
                    <div class="col-md-12 text-center">

                        <ul class="footer-payments">
                            <li><a href="#"><i class="fa fa-cc-visa"></i></a></li>
                            <li><a href="#"><i class="fa fa-credit-card"></i></a></li>
                            <li><a href="#"><i class="fa fa-cc-paypal"></i></a></li>
                            <li><a href="#"><i class="fa fa-cc-mastercard"></i></a></li>
                            <li><a href="#"><i class="fa fa-cc-discover"></i></a></li>
                            <li><a href="#"><i class="fa fa-cc-amex"></i></a></li>
                        </ul>
                        <span class="copyright">
                            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                            Copyright &copy;
                            <script>document.write(new Date().getFullYear());</script> All rights reserved | Nguyễn Hữu Nhân
                            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        </span>
                    </div>
                </div>
                <!-- /row -->
            </div>
            <!-- /container -->
        </div>
        <!-- /bottom footer -->
    </footer>
    <!-- /FOOTER -->
    <!-- jQuery Plugins <script src="~/Scripts/js/jquery.min.js"></script>
    <script src="~/Scripts/js/bootstrap.min.js"></script>
    <script src="~/Scripts/js/slick.min.js"></script>
    <script src="~/Scripts/js/nouislider.min.js"></script>
    <script src="~/Scripts/js/jquery.zoom.min.js"></script>
    <script src="~/Scripts/js/main.js"></script>-->

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
</body>
</html>