Areas/Admin/Controllers/KhachHangController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Website.Models;
namespace Website.Areas.Admin.Controllers
{
    public class KhachHangController : Controller
    {
        // GET: Admin/KhachHang
        dbWebsiteDataContext db = new dbWebsiteDataContext();
        public ActionResult Index()
        {
            return View(db.KHACHHANGs.ToList());
        }
        public ActionResult Search(string name)
        {
            if (!string.IsNullOrEmpty(name))
            {
                var kq = db.KHACHHANGs.Where(s => s.TenKH.Contains(name)||s.DienThoai.Contains(name));
                ViewBag.Search = name;
                return View(kq.ToList());
            }
            return View();
        }
        public ActionResult Delete(int id)
        {
            var nsp = db.KHACHHANGs.SingleOrDefault(n => n.MaKH == id);
            if (nsp == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            db.KHACHHANGs.DeleteOnSubmit(nsp);
            db.SubmitChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Details(int id)
        {
            var bl = db.KHACHHANGs.SingleOrDefault(n => n.MaKH == id);
            if (bl == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            return View(bl);
        }
        [HttpGet]
        public ActionResult Edit(int id)
        {
            var nsp = db.KHACHHANGs.SingleOrDefault(n => n.MaKH == id);
            if (nsp == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            return View(nsp);
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(FormCollection f)
        {
            var nsp = db.KHACHHANGs.SingleOrDefault(n => n.MaKH == int.Parse(f["MaKH"]));
            if (ModelState.IsValid)
            {
                
                nsp.TenKH = f["TenKH"];
                nsp.DiaChi = f["DiaChi"];
                nsp.DienThoai = f["DienThoai"];
                nsp.NgaySinh = Convert.ToDateTime(f["NgaySinh"]);
                nsp.Email = f["Email"];
                nsp.TaiKhoan = f["TaiKhoan"];
                nsp.MatKhau = f["MatKhau"];
                db.SubmitChanges();
                return RedirectToAction("Index");
            }
            return View(nsp);
        }
    }
}

Controllers/SearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Website.Models;

namespace Website.Controllers
{
    public class SearchController : Controller
    {
        // GET: Search
        dbWebsiteDataContext db = new dbWebsiteDataContext();
        public ActionResult Search(string name)
        {
            if (!string.IsNullOrEmpty(name))
            {   
                
                if (name == "LinhKien")
                {
                    var kqq = from lk in db.SANPHAMs where lk.MaLoaiSP > 9 && lk.MaLoaiSP < 15 select lk;
                    return View(kqq.ToList());
                }
                else if (name == "PhuKien")
                {
                    var kqq= from pk in db.SANPHAMs where pk.MaLoaiSP > 15 && pk.MaLoaiSP < 24 select pk;
                    return View(kqq.ToList());
                }
                else
                {
                var kq = db.SANPHAMs.Where(s => s.TenSP.Contains(name));
                //var kq = from s in db.SANPHAMs where s.TenSP == strSearch) select s;

                //var kq = db.SACHes.Where(s => s.MaCD == int.Parse(strSearch)).OrderByDescending(s => s.SoLuongBan);
                //var kq = from s in db.SACHes where s.MaCD == int.Parse(strSearch) orderby s.SoLuongBan descending select s ;
                ViewBag.Kq = kq.Count();
                ViewBag.Search = name;
                return View(kq.ToList());
                }
                
            }
            return View();
            
        }
    }
}

Areas/Admin/Views/KhachHang/Details.cshtml
@model Website.Models.KHACHHANG

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>CHI TIẾT</h2>

<div>
    <h4>Khách hàng</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Tên khách hàng
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenKH)
        </dd>

        <dt>
            Địa chỉ
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DiaChi)
        </dd>

        <dt>
            Số điện thoại
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DienThoai)
        </dd>

        <dt>
            Ngày sinh
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgaySinh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            Tài khoản
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TaiKhoan)
        </dd>

        <dt>
            Mật khẩu
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MatKhau)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.MaKH }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Areas/Admin/Views/KhachHang/Edit.cshtml
@model Website.Models.KHACHHANG

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>ĐIỀU CHỈNH</h2>

@using (Html.BeginForm("Edit", "KhachHang", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Khách hàng</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
       
        <div class="form-group">
            <label class="control-label col-md-2">Mã khách hàng</label>
            <div class="col-md-10">
                @*Chỉ hiển thị mã sách không cho sửa*@
                <input type="text" size="70" name="MaKH" value="@Model.MaKH" readonly class="form-control" />
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2">Tên khách hàng</label>
            <div class="col-md-10">
               
                <input type="text" size="70" name="TenKH" value="@Model.TenKH" class="form-control" />
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2">Địa chỉ</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.DiaChi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Số điện thoại</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.DienThoai, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DienThoai, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Ngày sinh</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.NgaySinh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NgaySinh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Tài khoản</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.TaiKhoan, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TaiKhoan, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Mật khẩu</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.MatKhau, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MatKhau, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Lưu" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Areas/Admin/Views/KhachHang/Index.cshtml
@{
    ViewBag.Title = "KhachHang";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
@model IEnumerable<Website.Models.KHACHHANG>
<h2>Danh mục Khách hàng</h2>
<div class="text-warning">
    @ViewBag.CusError
</div>
<hr />
<div>
    <div class="panel panel-default">
        <div class="panel-heading">
            <a class="btn btn-primary btn-default" href="@Url.Action("Index", "KhachHang")" role="button">Làm mới</a>
            <div class="form-group input-group navbar-right">
                @using (Html.BeginForm("Search", "KhachHang", FormMethod.Get))
                {
                    <input type="search" name="name" class="form-control" value="@ViewBag.Search" style="width:300px" placeholder="Nhập số điện thoại hoặc mã khách hàng..." />
                    <button class="btn btn-success" type="submit">
                        <i class="fa fa-search"></i>
                    </button>
                }
                </div>
        </div>
        <div class="panel-body">
            <div class="table-responsive table-bordered">
                <table class="table">
                    <thead>
                        <tr>
                            <th>Mã khách hàng</th>
                            <th>Tên khách hàng</th>
                            <th>Địa chỉ</th>
                            <th>Số điện thoại</th>
                            <th>Ngày sinh</th>
                            <th>Email</th>
                            <th>Chức năng</th>
                        </tr>
                    </thead>
                    <tbody>

                        @foreach (var item in Model)
                        {

                            <tr>
                                <td>@item.MaKH</td>
                                <td>@Html.DisplayFor(modelItem => item.TenKH)</td>
                                <td>@Html.DisplayFor(modelItem => item.DiaChi)</td>
                                <td>@Html.DisplayFor(modelItem => item.DienThoai)</td>
                                <td>@Html.FormatValue(@item.NgaySinh, "{0:dd/MM/yyyy}")</td>
                                <td>@Html.DisplayFor(modelItem => item.Email)</td>
                                <td>
                                    <a href="@Url.Action("Edit", "KhachHang",new { id= item.MaKH})"><i class="fa fa-pencil fa-fw"></i></a>|
                                    <a href="@Url.Action("Details", "KhachHang",new { id= item.MaKH})"><i class="fa fa-list-alt fa-fw"></i></a>|
                                    <a onclick="return confirm('Bạn có chắc chắn muốn xoá sản phẩm này?')" href="@Url.Action("Delete", "KhachHang",new { id= item.MaKH})"><i class="fa fa-times fa-fw"></i></a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            <!-- /.table-responsive -->
        </div>
        <!-- /.panel-body -->
    </div>
    <!-- /.panel -->
</div>

Areas/Admin/Views/KhachHang/Search.cshtml
@{
    ViewBag.Title = "Search";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
@model IEnumerable<Website.Models.KHACHHANG>
<h2>Danh mục Khách hàng</h2>
<div class="text-warning">
    @ViewBag.CusError
</div>
<hr />
<div>
    <div class="panel panel-default">
        <div class="panel-heading">
            <a class="btn btn-primary btn-default" href="@Url.Action("Index", "KhachHang")" role="button">Làm mới</a>
            <div class="form-group input-group navbar-right">
                @using (Html.BeginForm("Search", "KhachHang", FormMethod.Get))
                {
                    <input type="search" name="name" class="form-control" value="@ViewBag.Search" style="width:300px" placeholder="Nhập số điện thoại hoặc mã khách hàng..." />
                    <button class="btn btn-success" type="submit">
                        <i class="fa fa-search"></i>
                    </button>
                }
                </div>
        </div>
        <div class="panel-body">
            <div class="table-responsive table-bordered">
                <table class="table">
                    <thead>
                        <tr>
                            <th>Mã khách hàng</th>
                            <th>Tên khách hàng</th>
                            <th>Địa chỉ</th>
                            <th>Số điện thoại</th>
                            <th>Ngày sinh</th>
                            <th>Email</th>
                            <th>Chức năng</th>
                        </tr>
                    </thead>
                    <tbody>

                        @foreach (var item in Model)
                        {

                            <tr>
                                <td>@item.MaKH</td>
                                <td>@Html.DisplayFor(modelItem => item.TenKH)</td>
                                <td>@Html.DisplayFor(modelItem => item.DiaChi)</td>
                                <td>@Html.DisplayFor(modelItem => item.DienThoai)</td>
                                <td>@Html.FormatValue(@item.NgaySinh, "{0:dd/MM/yyyy}")</td>
                                <td>@Html.DisplayFor(modelItem => item.Email)</td>
                                <td>
                                    <a href="@Url.Action("Edit", "KhachHang",new { id= item.MaKH})"><i class="fa fa-pencil fa-fw"></i></a>|
                                    <a href="@Url.Action("Details", "KhachHang",new { id= item.MaKH})"><i class="fa fa-list-alt fa-fw"></i></a>|
                                    <a onclick="return confirm('Bạn có chắc chắn muốn xoá sản phẩm này?')" href="@Url.Action("Delete", "KhachHang",new { id= item.MaKH})"><i class="fa fa-times fa-fw"></i></a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            <!-- /.table-responsive -->
        </div>
        <!-- /.panel-body -->
    </div>
    <!-- /.panel -->
</div>